<!DOCTYPE html>
<html lang="en">
<head>
    <title>Homepage</title>
</head>
<body>
    <h3>This is a Homepage</h3>
    <p>
        <a href="/other-page">Go to other page</a>
    </p>
    <p>
        Get source: <a href="https://github.com/NewEXE/single-entry-point-php">Github</a>
        <br />
        Favicon was generated by <a href="https://favicon.io/favicon-generator/">Favicon generator</a>.
    </p>
    <p>
        <?= date('Y-m-d H:i:s') ?>
    </p>
</body>
</html>